
import type { Metadata, Viewport } from "next";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import AppProviders from "@/components/organisms/AppProviders";
import NavBar from "@/components/layout/nav-bar/NavBar";
import { Stack } from "@mui/material";
import { MainPageLayout } from "@/components/layout/MainPageLayout/MainPageLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <Stack flexDirection={'row'}>
            <NavBar />
            <MainPageLayout>
              {children}
            </MainPageLayout>
          </Stack>
        </AppProviders>
      </body>
    </html>
  );
}
